# Borrowed from github.com/exoplanet-dev/exoplanet
name: Style

on:
  push:
    branches:
      - main
      - luger
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U black
      - name: Check the style
        run: |
          black --check delicatessen
